/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseLoading: typeof import('./src/components/BaseLoading.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    Chat: typeof import('./src/components/Chat.vue')['default']
    ChatInput: typeof import('./src/components/ChatInput.vue')['default']
    ChatMessage: typeof import('./src/components/ChatMessage.vue')['default']
    ChooseGuide: typeof import('./src/components/ChooseGuide.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    GuideAvatar: typeof import('./src/components/GuideAvatar.vue')['default']
    GuidesStats: typeof import('./src/components/GuidesStats.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    Map: typeof import('./src/components/Map.vue')['default']
    MapMarker: typeof import('./src/components/MapMarker.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
