/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseLoading: typeof import('./src/components/BaseLoading.vue')['default']
    Button: typeof import('primevue/button')['default']
    ChooseTeam: typeof import('./src/components/ChooseTeam.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    Map: typeof import('./src/components/Map.vue')['default']
    MapMarker: typeof import('./src/components/MapMarker.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface GlobalDirectives {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
