/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/landmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Display a listing of the resource */
        get: operations["landmark.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/landmarks/{landmark}/reels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["reel.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["user.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/visits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["visit.index"];
        put?: never;
        post: operations["visit.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Landmark */
        Landmark: {
            id: number;
            name: string;
            localization_name: string;
            description: string;
            latitude: string;
            longitude: string;
            thumbnail_url: string;
            map_url: string;
            /** Format: date-time */
            created_at: string | null;
            /** Format: date-time */
            updated_at: string | null;
        };
        /** Reel */
        Reel: {
            id: number;
            media_url: string;
            landmark_id: number;
            /** Format: date-time */
            created_at: string | null;
            /** Format: date-time */
            updated_at: string | null;
        };
        /**
         * Team
         * @enum {string}
         */
        Team: Team;
        /** UserStoreRequest */
        UserStoreRequest: {
            team: components["schemas"]["Team"];
        };
        /** Visit */
        Visit: {
            id: number;
            user_id: number;
            landmark_id: number;
            team: components["schemas"]["Team"];
            /** Format: date-time */
            created_at: string | null;
            /** Format: date-time */
            updated_at: string | null;
        };
        /** VisitStoreRequest */
        VisitStoreRequest: {
            landmark_id: number;
        };
    };
    responses: {
        /** @description Validation error */
        ValidationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Errors overview. */
                    message: string;
                    /** @description A detailed description of each field that failed validation. */
                    errors: {
                        [key: string]: string[];
                    };
                };
            };
        };
        /** @description Not found */
        ModelNotFoundException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
        /** @description Unauthenticated */
        AuthenticationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "landmark.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Landmark"][];
                };
            };
        };
    };
    "reel.index": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The landmark ID */
                landmark: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reel"][];
                };
            };
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "user.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserStoreRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        access_token: string;
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "visit.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated set of `Visit` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        current_page: number;
                        data: components["schemas"]["Visit"][];
                        first_page_url: string | null;
                        from: number | null;
                        last_page_url: string | null;
                        last_page: number;
                        /** @description Generated paginator links. */
                        links: {
                            url: string | null;
                            label: string;
                            active: boolean;
                        }[];
                        next_page_url: string | null;
                        /** @description Base path for paginator generated URLs. */
                        path: string | null;
                        /** @description Number of items shown per page. */
                        per_page: number;
                        prev_page_url: string | null;
                        /** @description Number of the last item in the slice. */
                        to: number | null;
                        /** @description Total number of items being paginated. */
                        total: number;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "visit.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VisitStoreRequest"];
            };
        };
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["ValidationException"];
        };
    };
}
export enum Team {
    twardowski = "twardowski",
    rejewski = "rejewski",
    kazimierz_wielki = "kazimierz_wielki"
}
